import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";

export type DB = Database.Database;

// Single baseline schema. The app is still pre-release with no deployed databases, so the entire migration
// history was squashed into one CREATE-only baseline (no ALTER/backfill cruft). The framework (schema_version +
// the openDb loop below) is kept — post-release schema changes append a new entry to this array.
export const MIGRATIONS: ReadonlyArray<(db: DB) => void> = [
  (db) => {
    db.exec(`
      CREATE TABLE sessions (
        id              TEXT PRIMARY KEY,
        cwd             TEXT NOT NULL,
        status          TEXT NOT NULL DEFAULT 'active',
        sdk_session_id  TEXT,
        external_key    TEXT UNIQUE,
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        label           TEXT,          -- Master session label (auto-generated by Haiku). If null, the UI falls back to the cwd folder name.
        archived_at     TEXT,          -- Archive timestamp. If set, hidden from the list (restorable).
        origin          TEXT,          -- Session source: ui | slack | automation.
        origin_ref      TEXT,          -- Identifier within the source (slack = thread key, automation = automation id).
        pinned_at       TEXT           -- Pin timestamp for the sidebar 'pinned' section (isomorphic to archived_at).
      ) STRICT;

      CREATE TABLE messages (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id  TEXT NOT NULL REFERENCES sessions(id),
        role        TEXT NOT NULL,
        content     TEXT NOT NULL,
        created_at  TEXT NOT NULL
      ) STRICT;
      CREATE INDEX idx_messages_session ON messages(session_id, id);

      -- Master (session) transcript events — for restoring tool cards/thinking/metrics/notice (messages holds text only).
      CREATE TABLE session_events (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id    TEXT NOT NULL REFERENCES sessions(id),
        seq           INTEGER NOT NULL,
        type          TEXT NOT NULL,
        payload_json  TEXT NOT NULL,
        created_at    TEXT NOT NULL
      ) STRICT;
      CREATE INDEX idx_session_events ON session_events(session_id, seq);

      CREATE TABLE workers (
        id              TEXT PRIMARY KEY,
        session_id      TEXT NOT NULL REFERENCES sessions(id),
        repo_path       TEXT NOT NULL,
        label           TEXT NOT NULL,
        status          TEXT NOT NULL DEFAULT 'running',
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        worktree_path   TEXT,
        branch          TEXT,
        base            TEXT,
        sdk_session_id  TEXT,          -- Restore the conversation via resume after a daemon restart (idle instead of orphaned).
        model           TEXT,          -- The value fixed at spawn or live-changed by setModel (for UI display / restart consistency).
        archived_at     TEXT,
        ticket_key      TEXT,          -- Ticket/issue that spawned this worker (branch derivation + header shortcut). null = created directly.
        ticket_url      TEXT,
        notify_armed    INTEGER NOT NULL DEFAULT 0,                  -- One-shot flag: notify the master when this worker next settles.
        permission_mode TEXT NOT NULL DEFAULT 'bypassPermissions'   -- SDK permission mode (bypassPermissions | plan). Spawn-set, live-changeable.
      ) STRICT;
      CREATE INDEX idx_workers_session ON workers(session_id);

      CREATE TABLE worker_events (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        worker_id     TEXT NOT NULL REFERENCES workers(id),
        seq           INTEGER NOT NULL,
        type          TEXT NOT NULL,
        payload_json  TEXT NOT NULL,
        created_at    TEXT NOT NULL
      ) STRICT;
      CREATE INDEX idx_worker_events ON worker_events(worker_id, seq);

      -- Per-turn worktree checkpoint: a git snapshot sha for each seq (transcript position) → "revert to this turn".
      CREATE TABLE worker_checkpoints (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        worker_id     TEXT NOT NULL REFERENCES workers(id),
        seq           INTEGER NOT NULL,
        sha           TEXT NOT NULL,
        created_at    TEXT NOT NULL
      ) STRICT;
      CREATE INDEX idx_worker_checkpoints ON worker_checkpoints(worker_id, seq);

      CREATE TABLE memories (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        content     TEXT NOT NULL,
        tags        TEXT NOT NULL DEFAULT '',
        created_at  TEXT NOT NULL
      ) STRICT;

      CREATE TABLE repos (
        id          TEXT PRIMARY KEY,
        name        TEXT NOT NULL UNIQUE,
        path        TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        base        TEXT,
        remote_url  TEXT,
        created_at  TEXT NOT NULL,
        updated_at  TEXT NOT NULL
      ) STRICT;

      CREATE TABLE settings (
        key         TEXT PRIMARY KEY,
        value       TEXT NOT NULL,
        updated_at  TEXT NOT NULL
      ) STRICT;

      CREATE TABLE automations (
        id                  TEXT PRIMARY KEY,
        name                TEXT NOT NULL,
        enabled             INTEGER NOT NULL DEFAULT 0,
        trigger_type        TEXT NOT NULL,
        trigger_config_json TEXT NOT NULL,
        action_type         TEXT NOT NULL,
        action_config_json  TEXT NOT NULL,
        model               TEXT,
        effort              TEXT,
        next_run_at         TEXT,
        last_run_at         TEXT,
        last_status         TEXT,
        last_error          TEXT,
        created_at          TEXT NOT NULL,
        permission_mode     TEXT,          -- NULL = bypassPermissions (current behavior).
        max_turns           INTEGER        -- NULL = unlimited.
      ) STRICT;

      -- Worker completion notification queue (per session). Enqueued when an armed (notify_armed) worker settles.
      CREATE TABLE pending_notifications (
        id          INTEGER PRIMARY KEY,
        session_id  TEXT NOT NULL REFERENCES sessions(id),
        text        TEXT NOT NULL,
        created_at  TEXT NOT NULL
      ) STRICT;
      CREATE INDEX idx_pending_notifications_session ON pending_notifications(session_id);
    `);
  },
  (db) => {
    // Worker budget survives restart (audit #9): max_turns is the only unattended runaway guard and effort a
    // spawn-time override — both were in-memory-only, so a lazy resume (rehydrate→materialize) or a fork
    // silently ran uncapped at the global default effort. Nullable: NULL = unlimited / global default.
    db.exec("ALTER TABLE workers ADD COLUMN max_turns INTEGER");
    db.exec("ALTER TABLE workers ADD COLUMN effort TEXT");
  },
  (db) => {
    // workers.provider: which AgentBackend runs this worker ("claude" | "codex"). Default keeps
    // every pre-existing row on the Claude backend.
    db.exec("ALTER TABLE workers ADD COLUMN provider TEXT NOT NULL DEFAULT 'claude'");
  },
  (db) => {
    // sessions.provider: which AgentBackend runs this master session ("claude" | "codex"). Default keeps
    // every pre-existing row on the Claude backend (mirrors workers.provider above — see task-5-brief.md).
    db.exec("ALTER TABLE sessions ADD COLUMN provider TEXT NOT NULL DEFAULT 'claude'");
  },
];

export function currentVersion(db: DB): number {
  const row = db.prepare("SELECT version FROM schema_version").get() as
    | { version: number }
    | undefined;
  return row?.version ?? 0;
}

export function openDb(dbPath: string): DB {
  if (dbPath !== ":memory:") {
    fs.mkdirSync(path.dirname(dbPath), { recursive: true, mode: 0o700 });
  }
  const db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");
  db.pragma("busy_timeout = 5000");

  db.exec("CREATE TABLE IF NOT EXISTS schema_version (version INTEGER NOT NULL)");
  const migrate = db.transaction(() => {
    const from = currentVersion(db);
    if (from > MIGRATIONS.length) {
      throw new Error(`DB schema version ${from} is newer than this build (${MIGRATIONS.length}). Use a matching daemon version.`);
    }
    for (let v = from; v < MIGRATIONS.length; v++) {
      MIGRATIONS[v]!(db);
    }
    db.prepare("DELETE FROM schema_version").run();
    db.prepare("INSERT INTO schema_version(version) VALUES (?)").run(MIGRATIONS.length);
  });
  try {
    migrate();
  } catch (err) {
    db.close();
    throw err;
  }
  return db;
}
